export const homeData = [
  {
    id: 1,
    name: "The Panda",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Legendary warrior Po teams up with an elite English knight on a global quest to rescue magical weapons, restore his reputation and save the world!",
    starring: "Jack Black,Rita Ora,James Hong",
    genres: "comedy",
    tags: "Action, Adventures, comedy",
    cover: "../images/home1.jpg",
    video: "../video/video1.mp4",
    date: "20-Jan-2020",
  },
  {
    id: 2,
    name: " ZOMBIES",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "A high school becomes ground zero for a zombie virus outbreak. Trapped students must fight their way out or turn into one of the rabid infected.",
    starring: " Park Ji-hu,Yoon Chan-young,Cho Yi-hyun",
    genres: "Horror",
    tags: " Horror Adventures,Family",
    cover: "../images/home2.jpg",
    video: "../video/video2.mp4",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "heart of stones",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "An intelligence operative for a shadowy global peacekeeping agency races to stop a hacker from stealing its most valuable and dangerous weapon.",
    starring: "Gal Gadot,Jamie Dornan,Alia Bhatt",
    genres: "Action",
    tags: "Adventures,Action ",
    cover: "../images/home3.jpg",
    video: "../video/video3.mp4",
    date: "20-FEB-2023",
  },
  {
    id: 4,
    name: "hiddenstrike",
    rating: 4.9,
    time: "2hr : 22mins",
    desc: "Two elite soldiers must escort civilians through a gauntlet of gunfire and explosions in this film starring Jackie Chan and John Cena.",
    starring: "Jackie Chan,John Cena,Pilou Asbæk",
    genres: "Action",
    tags: "Action, Adventures",
    cover: "../images/home4.jpg",
    video: "../video/video4.mp4",
    date: "12-Aug-2023",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/u1.jpg",
    name: "Dog done",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u2.jpg",
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "jung-e",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u4.jpg",
    name: "The Magician’s Elephant",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u5.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.png",
    name: "King of Jungle",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u7.jpg",
    name: "The illusion",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u8.jpg",
    name: "jawan",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u9.jpg",
    name: "satya prem ki katha",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u10.jpg",
    name: "The Three Days",
    time: "2hr : 38mins",
  },
]

export const trending = [
  {
    id: 1,
    name: "Dark",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery that spans three generations.",

    starring: "Louis Hofmann,Oliver Masucci,Jördis Triebel",
    genres: "Triller",
    tags: "Action, triller, Horror",
    cover: "../images/img/slide1.jpg",
    date: "20-Jan-2023",
  },
  {
    id: 2,
    name: "Love Again",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "Still grieving her fiance's death, an artist texts her deepest thoughts to his phone and forms a bond with the man who receives them by chance. ",
    starring: "Priyanka Chopra Jonas,Sam Heughan,Céline Dion",
    genres: "comedy",
    tags: "comedy,Family",
    cover: "../images/img/slide2.jpg",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Arriaval",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "When alien ships land around the globe, a language expert tasked with deciphering their communications uncovers a life-altering message.",
    starring: "Amy Adams,Jeremy Renner,Forest Whitaker",
    genres: "sci-fi",
    tags: "Adventures,sci-fi ",
    cover: "../images/img/slide3.jpg",
    date: "20-FEB-2020",
  },
]
export const recommended = [
  {
    id: 1,
    cover: "../images/rec/rec1.jpg",
    name: "Emily In Paris",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/rec/rec2.jpg",
    name: " Mismatch",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/rec/rec3.jpg",
    name: "Never Have I ever",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/rec/rec4.jpg",
    name: "Stranger Things",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/rec/rec5.jpg",
    name: "wednesday",
    time: "2hr : 38mins",
  },
]
